### ISSUE TITLE
testcase "wallLaw" problem

### ISSUE THREAD

**Issue by fordao07** [mnucci32/cfd3d#5]
Hi, 
I compiled aither  0.7,  0.8 and 0.9 with  mingw64-gcc-7.2.0. 
When I used aither 0.8 and 0.9 to run testcase "wallLaw"  , it diverged.

>    aither.exe wallLaw.inp

Aither version 0.9.0

Using MPI Version 2.0
Using 1 process
...
Solution Initialized

Starting wall distance calculation...
Building k-d tree...
K-d tree complete after 0.001 seconds
Wall distance calculation finished after 0.005 seconds

Step   NL-Iter CFL         Res-Mass    Res-Mom-X   Res-Mom-Y   Res-Mom-Z   Res-Energy  Res-Tke     Res-Omega   Max-Eqn Max-Blk Max-I   Max-J   Max-K   Max-Res     Res-Matrix  
0      0       1.0000e+005 1.0000e+000 1.0000e+000 1.0000e+000 1.0000e+000 1.0000e+000 1.0000e+000 1.0000e+000 7       1       43      0       49      9.7871e-005 4.3013e-006 
1      0       1.0000e+005 1.0000e+000 1.0000e+000 1.0000e+000 1.0000e+000 1.0000e+000 2.5130e-001 2.4990e-001 7       1       43      0       49      2.4468e-005 4.1449e-006 
2      0       1.0000e+005 1.0000e+000 7.1224e-001 9.6398e-001 1.0000e+000 1.0000e+000 6.8091e-002 6.2386e-002 7       1       43      0       49      6.1172e-006 3.9928e-006 
3      0       1.0000e+005 9.8850e-001 3.9045e-001 9.3568e-001 9.9755e-001 9.6239e-001 3.3149e-002 1.5522e-002 7       1       43      0       49      1.5293e-006 3.9684e-006 
4      0       1.0000e+005 9.2346e-001 1.9283e-001 8.1248e-001 9.9364e-001 8.8481e-001 3.6305e-002 3.8299e-003 4       1       43      1       0       1.1384e-006 3.9894e-006 
5      0       1.0000e+005 9.4928e-001 3.9470e-001 6.6706e-001 9.9185e-001 9.1497e-001 4.1454e-002 9.4175e-004 4       1       43      1       0       1.1356e-006 3.9816e-006 
6      0       1.0000e+005 9.5494e-001 4.6842e-001 5.5901e-001 9.8892e-001 9.2872e-001 4.3889e-002 2.3460e-004 4       1       43      1       0       1.1316e-006 3.9248e-006 
7      0       1.0000e+005 9.1889e-001 4.2973e-001 4.6601e-001 9.8469e-001 9.0084e-001 4.2301e-002 5.8226e-005 4       1       43      1       0       1.1258e-006 3.8122e-006 
8      0       1.0000e+005 8.5154e-001 3.4667e-001 3.7878e-001 9.7976e-001 8.3965e-001 3.9947e-002 1.4301e-005 4       1       43      1       0       1.1204e-006 3.6659e-006 
9      0       1.0000e+005 7.7443e-001 2.3396e-001 3.3584e-001 9.7419e-001 7.6777e-001 3.8762e-002 3.5722e-006 4       1       43      1       0       1.1149e-006 3.5319e-006 
10     0       1.0000e+005 7.0625e-001 1.5049e-001 3.1234e-001 9.6865e-001 7.0398e-001 3.7521e-002 9.1465e-007 4       1       43      1       0       1.1093e-006 3.4555e-006 
11     0       1.0000e+005 6.5928e-001 1.7453e-001 2.8181e-001 9.6338e-001 6.6149e-001 3.6356e-002 4.3135e-007 4       1       43      0       0       1.1038e-006 3.4374e-006 
12     0       1.0000e+005 6.4261e-001 2.1936e-001 2.5715e-001 9.5859e-001 6.4645e-001 3.4982e-002 2.9807e-007 4       1       43      0       0       1.0987e-006 3.4386e-006 
13     0       1.0000e+005 6.5211e-001 2.1558e-001 2.5682e-001 9.5425e-001 6.5743e-001 3.3547e-002 2.7174e-007 4       1       43      0       0       1.0942e-006 3.4259e-006 
14     0       1.0000e+005 6.8016e-001 1.6861e-001 2.7228e-001 9.5019e-001 6.8533e-001 3.2070e-002 2.4710e-007 4       1       43      1       0       1.0896e-006 3.3938e-006 
15     0       1.0000e+005 7.1011e-001 1.0676e-001 2.8788e-001 9.4615e-001 7.1627e-001 3.0600e-002 2.3059e-007 4       1       43      1       0       1.0846e-006 3.3534e-006 
16     0       1.0000e+005 7.3905e-001 8.0334e-002 2.8828e-001 9.4198e-001 7.4514e-001 2.9167e-002 2.2721e-007 4       1       43      1       0       1.0795e-006 3.3147e-006 
17     0       1.0000e+005 7.5547e-001 1.0731e-001 2.7228e-001 9.3750e-001 7.6289e-001 2.7784e-002 2.2705e-007 4       1       43      1       0       1.0740e-006 3.2813e-006 
18     0       1.0000e+005 7.5846e-001 1.3338e-001 2.4946e-001 9.3261e-001 7.6603e-001 2.6456e-002 3.4511e-007 4       1       43      1       0       1.0680e-006 3.2586e-006 
19     0       1.0000e+005 7.4542e-001 1.3294e-001 2.3004e-001 9.2727e-001 7.5387e-001 2.5184e-002 3.9144e-007 4       1       43      1       0       1.0617e-006 3.2460e-006 
20     0       1.0000e+005 7.2167e-001 1.0753e-001 2.1462e-001 9.2162e-001 7.2973e-001 2.3963e-002 2.2378e-007 4       1       43      1       0       1.0553e-006 3.2332e-006 
21     0       1.0000e+005 6.9312e-001 7.2727e-002 2.0311e-001 9.1582e-001 7.0168e-001 2.2789e-002 9.2509e+005 4       1       43      1       0       1.0489e-006 5.0983e+003 
22     0       1.0000e+005 6.6395e-001 5.4209e-002 3.0390e-001 9.2357e-001 6.7157e-001 1.4645e+008 3.2809e+019 7       1       1       0       1       4.9387e+014 4.5384e+017 
23     0       1.0000e+005 6.8313e-001 6.8069e-002 4.6876e-001 1.3394e+000 7.2029e-001 3.7548e+022 5.3049e+046 7       1       17      1       0       1.1533e+043 4.3958e+029 
24     0       1.0000e+005 1.1378e+000 6.9496e-002 6.1930e-001 9.4158e-001 1.1525e+000 7.2106e+036 5.8892e+073 7       1       25      1       0       2.4756e+070 1.3644e+033 
25     0       1.0000e+005 1.1563e+000 5.1447e-002 6.3364e-001 9.4104e-001 1.1718e+000 1.8027e+036 2.9989e+083 7       1       40      1       0       1.2080e+080 3.4762e+024 
26     0       1.0000e+005 1.1585e+000 3.1310e-002 6.4808e-001 9.4103e-001 1.1742e+000 4.5068e+035 7.4975e+082 7       1       40      1       0       3.0201e+079 4.9095e+018 
27     0       1.0000e+005 1.1607e+000 2.5005e-002 6.5924e-001 9.4102e-001 1.1769e+000 1.1267e+035 1.8744e+082 7       1       40      1       0       7.5505e+078 2.3099e+015 
28     0       1.0000e+005 1.1622e+000 2.8246e-002 6.6737e-001 9.4100e-001 1.1785e+000 2.8169e+034 4.6862e+081 7       1       40      1       0       1.8877e+078 1.5465e+007 
29     0       1.0000e+005 1.1635e+000 2.9222e-002 6.7416e-001 9.4099e-001 1.1801e+000 7.0423e+033 1.1716e+081 7       1       40      1       0       4.7193e+077 3.0903e+018 
30     0       1.0000e+005 1.1643e+000 2.9030e-002 6.7699e-001 9.4103e-001 1.1809e+000 1.7606e+033 2.9290e+080 7       1       40      1       0       1.1798e+077 4.0000e+020 
31     0       1.0000e+005 1.1659e+000 2.7071e-002 6.7778e-001 9.4108e-001 1.1826e+000 4.4016e+032 7.3226e+079 7       1       40      1       0       2.9497e+076 2.6632e+029 
32     0       1.0000e+005 1.1644e+000 2.4126e-002 6.8311e-001 9.4102e-001 1.1810e+000 4.9745e+033 1.8307e+079 7       1       40      1       0       7.3744e+075 1.9236e+039 
33     0       1.0000e+005 1.1632e+000 1.9522e-002 6.8181e-001 9.4095e-001 1.1799e+000 6.7302e+045 9.9785e+095 7       1       38      1       1       6.1524e+092 2.2847e+048 
34     0       1.0000e+005 1.1631e+000 1.5612e-002 6.8524e-001 9.4095e-001 1.1797e+000 3.8707e+055 1.0326e+118 7       1       37      1       2       6.3842e+114 9.5467e+059 
35     0       1.0000e+005 1.1650e+000 1.2731e-002 6.7351e-001 9.4096e-001 1.1817e+000 7.2584e+063 4.4387e+136 7       1       36      1       3       2.7449e+133 8.1670e+061 
36     0       1.0000e+005 1.1637e+000 1.2200e-002 6.7306e-001 9.4091e-001 1.1804e+000 1.3762e+071 2.5891e+153 7       1       35      1       4       1.6005e+150 1.0880e+066 
37     0       1.0000e+005 1.1687e+000 1.1836e-002 6.5227e-001 9.4091e-001 1.1857e+000 3.2421e+076 inf         7       1       34      1       2       1.9387e+159 1.6875e+071 
38     0       1.0000e+005 1.1662e+000 1.2774e-002 6.5520e-001 9.4080e-001 1.1832e+000 4.7230e+081 inf         7       1       33      1       2       8.8938e+169 5.4994e+072 
39     0       1.0000e+005 1.1692e+000 1.1605e-002 6.5599e-001 9.4089e-001 1.1865e+000 3.2782e+081 inf         7       1       32      1       4       1.1045e+173 2.2026e+085 
40     0       1.0000e+005 1.1701e+000 9.5711e-003 6.5959e-001 9.4092e-001 1.1875e+000 4.9896e+086 inf         7       1       31      1       5       5.8543e+185 8.9803e+091 
41     0       1.0000e+005 1.1699e+000 9.0252e-003 6.6302e-001 9.4092e-001 1.1875e+000 9.1287e+086 inf         7       1       30      1       6       6.8103e+195 4.7369e+093 
42     0       1.0000e+005 1.1713e+000 1.0554e-002 6.5114e-001 9.4091e-001 1.1889e+000 2.4935e+090 inf         7       1       29      1       7       3.9440e+199 7.7202e+093 
43     0       1.0000e+005 1.1742e+000 1.2945e-002 6.2504e-001 9.4078e-001 1.1920e+000 2.2346e+090 inf         7       1       28      1       8       2.2063e+200 3.9118e+089 
44     0       1.0000e+005 1.1738e+000 1.6261e-002 6.0488e-001 9.4087e-001 1.1915e+000 5.5891e+089 inf         7       1       28      1       8       5.5158e+199 5.8233e+087 
45     0       1.0000e+005 1.1735e+000 1.8926e-002 6.0526e-001 9.4338e-001 1.3151e+000 1.3973e+089 inf         7       1       28      1       8       1.3790e+199 9.1242e+085 
46     0       1.0000e+005 8.5801e+000 1.8983e-001 1.5742e+001 9.6591e-001 8.8798e+000 3.4934e+088 inf         7       1       28      1       8       3.4475e+198 2.7798e+088 
47     0       1.0000e+005 6.7315e+000 3.5800e-001 1.4712e+001 9.5586e-001 6.8583e+000 5.8884e+091 inf         7       1       28      1       8       8.6190e+197 1.3571e+098 
48     0       1.0000e+005 6.7857e+000 3.9656e-001 1.8156e+001 9.5619e-001 6.9166e+000 1.6092e+102 inf         7       0       0       0       6       1.0755e+204 1.8845e+085 
49     0       1.0000e+005 8.4660e+000 4.2490e-001 2.1498e+001 9.6485e-001 8.6314e+000 4.0232e+101 inf         7       0       0       0       6       2.6889e+203 2.8741e+098 
50     0       1.0000e+005 8.4661e+000 4.2489e-001 2.1498e+001 9.6489e-001 8.6315e+000 9.2449e+107 inf         7       0       1       5       12      2.6687e+212 1.6176e+112 
51     0       1.0000e+005 8.4662e+000 4.2490e-001 2.1498e+001 9.6493e-001 8.6317e+000 7.5542e+121 inf         7       0       1       5       11      3.1970e+240 2.5116e+124 
52     0       1.0000e+005 8.4664e+000 4.2490e-001 2.1498e+001 9.6497e-001 8.6318e+000 8.9802e+137 inf         7       0       1       0       10      1.9606e+268 6.6467e+135 
53     0       1.0000e+005 8.4665e+000 4.2491e-001 2.1498e+001 9.6501e-001 8.6320e+000 4.1032e+140 inf         7       0       0       1       10      4.0153e+289 7.1719e+145 
54     0       1.0000e+005 8.4667e+000 4.2491e-001 2.1498e+001 9.6506e-001 8.6321e+000 8.4655e+148 inf         7       0       1       4       8       inf         nan         
Assert failed: nonphysical density
Condition: state_(ii, jj, kk).Rho() > 0
At: aither-0.9.0\src\procBlock.cpp:909

**Comment by mnucci32** [comment]
I think the CFL number you are running with is too high. The test case uses a value of 100, and you are using 1e5. I think it should run for you if you drop that value
