### ISSUE TITLE
How to visualize output with Paraview

### ISSUE THREAD

**Issue by nyue** [mnucci32/cfd3d#6]
## Issue Type (bug, feature request, other)
other

## Description of Issue
Could you write up a set of simple steps to visualize the output from one of the sample simulation using Paraview which is able to load Plot3D files, using a simple sample e.g. couette ?

**Comment by mnucci32** [comment]
When you run a simulation like the couette example, the code will output `.p3d`, `.fun`, and `.xyz` files. The `.xyz` file is a Plot3D grid file, the `.fun` file is a Plot3D function file, and the `.p3d` file is a meta file for ParaView. To visualize a solution in ParaView choose **File->Open** and pick the `.p3d` file. That's all there is to it! 

The `.p3d` file points to the `.xyz` and `.fun` files, so ParaView knows to load them as well. When a simulation is run in a steady state manner, the `.p3d` file points to a single solution (the last one). When a simulation is run time accurate the `.p3d` file points to a series of solutions so multiple `.fun` files are loaded into ParaView and an animation of the simulation can be visualized. ParaView 5.3 or newer is required for visualization.

I hope this helps. Let me know if you have further questions.
